# Default Training Configuration for Steel Casting Defect Prediction
# This configuration provides sensible defaults for model training

# Data Configuration
data:
  target_column: "defect"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  handle_missing: true

# Model Configuration
model:
  type: "xgboost"
  parameters:
    objective: "binary:logistic"
    eval_metric: "auc"
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 1
    gamma: 0
    reg_alpha: 0
    reg_lambda: 1
    random_state: 42
    n_jobs: -1
    verbosity: 0

# Training Configuration
training:
  hyperparameter_search: true
  search_method: "grid"
  cross_validation: true
  cv_folds: 5
  early_stopping: false
  early_stopping_rounds: 10

# Preprocessing Configuration
preprocessing:
  scaling_method: "standard"
  handle_missing: true
  missing_strategy: "median"
  categorical_strategy: "most_frequent"

# Hyperparameter Search Configuration
hyperparameter_search:
  enabled: true
  method: "grid"
  n_iter: 50
  cv_folds: 5
  scoring: "roc_auc"
  param_grids:
    coarse:
      n_estimators: [50, 100, 200]
      max_depth: [3, 6, 9]
      learning_rate: [0.05, 0.1, 0.2]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]
    fine:
      n_estimators: [80, 100, 120]
      max_depth: [5, 6, 7]
      learning_rate: [0.08, 0.1, 0.12]
      subsample: [0.7, 0.8, 0.9]
      colsample_bytree: [0.7, 0.8, 0.9]
      min_child_weight: [1, 3, 5]
      gamma: [0, 0.1, 0.2]
    extensive:
      n_estimators: [50, 100, 150, 200, 300]
      max_depth: [3, 4, 5, 6, 7, 8, 9]
      learning_rate: [0.01, 0.05, 0.1, 0.15, 0.2]
      subsample: [0.6, 0.7, 0.8, 0.9, 1.0]
      colsample_bytree: [0.6, 0.7, 0.8, 0.9, 1.0]
      min_child_weight: [1, 3, 5, 7]
      gamma: [0, 0.1, 0.2, 0.3]
      reg_alpha: [0, 0.1, 0.5, 1.0]
      reg_lambda: [0.5, 1.0, 1.5, 2.0]

# Output Configuration
output:
  save_artifacts: true
  experiment_name_prefix: "baseline"
  output_dir: "results"

# Execution Configuration
execution:
  verbose: true
  n_jobs: -1
  random_state: 42
