evaluation:
  # General Settings
  settings:
    default_threshold: 0.5
    output_directory: "results/evaluation"
    save_plots: true
    plot_format: "png"  # png, pdf, svg
    plot_dpi: 300
    
  # Metrics Configuration
  metrics:
    # Basic Classification Metrics
    basic:
      - "accuracy"
      - "balanced_accuracy"
      - "precision"
      - "recall"
      - "f1_score"
      - "specificity"
      - "matthews_corrcoef"
      
    # Probabilistic Metrics
    probabilistic:
      - "roc_auc"
      - "average_precision"
      - "log_loss"
      - "brier_score"
      
    # Custom Domain-Specific Metrics
    custom:
      - "defect_detection_rate"
      - "false_alarm_rate"
      - "production_impact_score"
      - "quality_efficiency_score"
      
  # Cross-Validation Settings
  cross_validation:
    cv_folds: 5
    stratify: true
    shuffle: true
    scoring_metrics:
      - "roc_auc"
      - "average_precision"
      - "f1"
      - "precision"
      - "recall"
      
  # Plotting Configuration
  plotting:
    # Figure Settings
    figure:
      style: "seaborn"  # seaborn, ggplot, default
      context: "paper"  # paper, notebook, talk, poster
      palette: "Set2"
      
    # ROC Curve Settings
    roc_curve:
      show_diagonal: true
      show_thresholds: false
      optimal_threshold_method: "youden"  # youden, f1, precision_recall
      
    # PR Curve Settings
    pr_curve:
      show_baseline: true
      show_thresholds: false
      
    # Confusion Matrix Settings
    confusion_matrix:
      normalize: null  # null, 'true', 'pred', 'all'
      colormap: "Blues"
      show_values: true
      
    # Feature Importance Settings
    feature_importance:
      max_features: 20
      orientation: "horizontal"  # horizontal, vertical
      include_error_bars: true
      
  # Report Generation
  reporting:
    include_sections:
      - "executive_summary"
      - "detailed_metrics"
      - "confusion_matrix"
      - "roc_pr_curves"
      - "feature_importance"
      - "cross_validation"
      - "calibration_analysis"
      
    formats:
      - "html"
      - "markdown"
      - "json"
      
  # Cost Matrix for Production Impact
  cost_matrix:
    # Costs for steel defect prediction
    # [True Negative, False Positive]
    # [False Negative, True Positive]
    values: [[0, 10], [100, 0]]  # Missing defects costs 10x more than false alarms
    
  # Threshold Optimization
  threshold_optimization:
    methods:
      - "youden"
      - "f1"
      - "precision_recall_balance"
      - "cost_sensitive"
    search_range: [0.1, 0.9]
    search_points: 100
    
  # Bootstrap Configuration
  bootstrap:
    n_samples: 1000
    confidence_level: 0.95
    random_state: 42
    
  # Statistical Testing
  statistical_tests:
    significance_level: 0.05
    default_test: "paired_ttest"  # paired_ttest, wilcoxon, mannwhitneyu
    multiple_comparisons: "bonferroni"  # bonferroni, fdr_bh, none