baseline_model:
  algorithm: "xgboost"
  parameters:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
  
  feature_engineering:
    statistical_features: true
    stability_features: true
    duration_features: true
    interaction_features: true
    
  validation:
    cv_folds: 5
    early_stopping_rounds: 10
    eval_metric: "auc"

lstm_model:
  architecture:
    input_size: 5  # Number of sensors
    hidden_size: 64
    num_layers: 2
    dropout: 0.2
    bidirectional: false
    
  training:
    batch_size: 32
    learning_rate: 0.001
    num_epochs: 100
    early_stopping_patience: 15
    weight_decay: 1e-4
    
  data_processing:
    sequence_length: 300  # 5 minutes at 1Hz
    normalization: "z_score"
    padding: "zero"
    
  loss_function:
    type: "weighted_bce"
    pos_weight: 3.0  # For class imbalance

evaluation:
  metrics:
    - "auc_roc"
    - "auc_pr"
    - "f1_score"
    - "precision"
    - "recall"
    - "accuracy"
  
  test_size: 0.2
  stratify: true
  random_state: 42