# Quick Training Configuration for Development
# Reduced settings for faster iteration during development

# Data Configuration  
data:
  target_column: "defect"
  test_size: 0.2
  validation_size: 0.2
  random_state: 42
  handle_missing: true

# Model Configuration
model:
  type: "xgboost"
  parameters:
    objective: "binary:logistic"
    eval_metric: "auc"
    n_estimators: 50  # Reduced for speed
    max_depth: 4      # Reduced for speed
    learning_rate: 0.1
    subsample: 0.8
    colsample_bytree: 0.8
    random_state: 42
    n_jobs: -1
    verbosity: 0

# Training Configuration
training:
  hyperparameter_search: true
  search_method: "random"  # Faster than grid search
  cross_validation: true
  cv_folds: 3              # Reduced for speed
  early_stopping: false
  early_stopping_rounds: 5

# Preprocessing Configuration
preprocessing:
  scaling_method: "standard"
  handle_missing: true
  missing_strategy: "median"
  categorical_strategy: "most_frequent"

# Hyperparameter Search Configuration
hyperparameter_search:
  enabled: true
  method: "random"
  n_iter: 10              # Much smaller search space
  cv_folds: 3
  scoring: "roc_auc"
  param_grids:
    quick:
      n_estimators: [30, 50, 100]
      max_depth: [3, 4, 6]
      learning_rate: [0.1, 0.2]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]

# Output Configuration
output:
  save_artifacts: true
  experiment_name_prefix: "quick"
  output_dir: "results"

# Execution Configuration
execution:
  verbose: true
  n_jobs: -1
  random_state: 42